local _, addon = ...;
local L = addon.Localization.GetDefaultLocale();
addon.L = L;

-- [[ https://legacy.curseforge.com/wow/addons/krowi-brokers-currency/localization ]] --
-- [[ Everything after this line is automatically generated from CurseForge and is not meant for manual edit - SOURCETOKEN - AUTOGENTOKEN ]] --

-- [[ Exported at 2026-01-06 22-42-26 ]] --
L["1 Hour"] = true
L["12 Hours"] = true
L["2 Hours"] = true
L["24 Hours"] = true
L["4 Hours"] = true
L["48 Hours"] = true
L["8 Hours"] = true
L["Account Total"] = true
L["Alliance:"] = true
L["Button Display"] = true
L["Character Gold"] = true
L["Characters:"] = true
L["Combined"] = true
L["Copper Label"] = "c"
L["Currency"] = true
L["Currency Group By Header"] = true
L["Currency Hide Unused"] = true
L["Current Faction Total"] = true
L["Data will be collected as you play"] = true
L["Default Tooltip"] = true
L["Earned:"] = true
L["Faction Totals:"] = true
L["Gold Label"] = "g"
L["Header Visibility"] = true
L["Hold Ctrl: Show currencies"] = true
L["Hold Shift: Show currencies"] = true
L["Hold Shift: Show money"] = true
L["Horde:"] = true
L["Max Characters"] = true
L["Money"] = true
L["more characters"] = true
L["No character data available yet"] = true
L["Realm Total"] = true
L["Release Ctrl: Show combined"] = true
L["Release Shift: Show combined"] = true
L["Release Shift: Show currencies"] = true
L["Release Shift: Show money"] = true
L["Right-Click: Options"] = true
L["Session Duration"] = true
L["Session:"] = true
L["Show On Button"] = true
L["Show WoW Token"] = true
L["Silver Label"] = "s"
L["Spent:"] = true
L["Tooltip Options"] = true
L["Total:"] = true
L["Track All Realms"] = true
L["Track Session Gold"] = true
L["Warband Bank"] = true
L["Warband Bank:"] = true
L["WoW Token:"] = true